/** Declaration file generated by dts-gen */

import 'baffle'

declare module 'baffle' {
  // function baffleFinc(t: any, e: any): any
  export function once(): void
  export function start(): void
}

// declare function baffle(t: any, e: any): any;
