export { default as Main } from './Main'
export { default as Board } from './Board'
export { default as History } from './History'
export { default as Art } from './Art'
export { default as Travel } from './Travel'
